config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  namespace :admin do
      resources :arts
      resources :articles
      resources :cats
      resources :lists
      resources :posts
      resources :tags
      resources :taggables
      resources :blogs
      resources :users

      root to: "arts#index"
    end
  resources :cats
  resources :posts
  resources :tags
  resources :articles
  get 'home/index'
  resources :arts
  devise_for :users
  resources :lists
  get "up" => "rails/health#show", as: :rails_health_check
  # root "posts#index"
  #root "lists#index"
  root "home#index"
  #root "arts#index"
  #root "cats#index"
end

app/models/article.rb
class Article < ApplicationRecord
  async_pluck
  belongs_to :user
  has_many :taggables, dependent: :destroy
  has_many :tags, through: :taggables
  has_one_attached :image
  has_many_attached :pictures
  has_rich_text :body
  accepts_nested_attributes_for :tags, allow_destroy: true,
   :reject_if => lambda { |a| a[:name].blank? }

  def image_as_thumbnail
    return unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    image.variant(resize_to_limit: [300, 300]).processed
  end
  def pictures_as_thumbnails
    pictures.map do |picture|
      picture.variant(resize_to_limit: [150, 150]).processed
    end
  end
  def pictures_as_thumbnails(article)
    article.variant(resize_to_limit: [200, 200]).processed
  end
end

app/controllers/admin/articles_controller.rb
module Admin
  class ArticlesController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes(action_name)).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-demo.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  def index
    @articles = Article.all
    if params[:tag_id]
      Tag.find(id).articles
    else
      @articles = Article.all.order('created_at DESC')
    end
    @pagy, @articles = pagy(@articles)
    if params[:query].present?
      @articles = Article.where("title LIKE ?", "%#{params[:query]}%")
    end

    if turbo_frame_request?
      render partial: "articles", locals: { articles: @articles }
    else
      render :index
    end
  rescue Pagy::OverflowError
    #redirect_to root_path(page: 1)
    params[:page] = 1
    retry
  end

  def tags
    @article = Article.find(params[:id])
  end

  def show
    @article = Article.find(params[:id])
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
      @tag = @articles
    end
    #@related_articles = Article.tagged_with(
    #  @article.tag_lists, any: true)
  end

  def new
    @article = Article.new
    @tags = Tag.all
    #@tags = Tag.find(:all)
    taggable = @article.taggables.build()
    #article_tag = @article.article_tags.build()
    #@taggables = @article.tags.all
    @article.taggables.build.build_tag
    3.times do
      @taggables = @article.taggables.build()
      #article_tag = @article.article_tags.build()
    end
  end

  def search
  #  return nil if params[:keyword] == ""
  #  tag = Tag.where(['name LIKE ?',
  #    "%#{params[:keyword]}%"] )
  #  render json:{ keyword: tag }
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def upvote
    @article.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @article.downvote_by current_user
    redirect_to :back
  end

  private
    def set_article
      @article = Article.find(params[:id])
    end

    def venue_params
      params.require(:venue).permit(:name, :address, :discount, :latitude, :longitude, :tags_attributes =>[:name],:tag_ids => [])
    end
    def find_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(
        :title, :name, :image, :body,
        :publish, pictures: []
      ).with_defaults(user: current_user)
    end

    def current_user
      User.first
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= article.user_id %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= article.title %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= article.name %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Publish:</strong>
    <%= article.publish %>
  </p>
  <p class="my-5">
    <strong class="block font-medium mb-1">Body:</strong>
    <%= article.body %>
  </p>
  <% if action_name != "show" %>
    <%= link_to "Show this article", article, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this article", edit_article_path(article), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/articles/_articles.html.erb
<!-- app/views/articles/_articles.html.erb-->
<%= turbo_frame_tag "articles" do %>
  <%= render articles %>
<% end >

app/views/articles/_f.html.erb
<div class="my-5">
  <%= form.label :user_id %>
  <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
</div>

app/views/articles/_form.html.erb
<%= form_with(model: article, class: "contents") do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title,
    class: "block shadow rounded-md border border-gray-200
    dark:text-slate-800 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name,
    class: "block shadow rounded-md border border-gray-200
    dark:text-slate-800 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div class="my-4">
    <%= form.label :tag, style: "display: block" %>
    <%= form.text_field :tags, class: "dark:text-slate-800",
    value: article.tags.map(&:name).join(",") %>
  </div>
  <div>
    <%= form.label :image, style: "display: block" %>
    <%= form.file_field :image %>
  </div>
  <div class="my-5">
    <%= form.label :publish %>
    <%= form.date_field :publish,
    class: "block shadow rounded-md border border-gray-200
    dark:text-slate-800 outline-none px-3 py-2 mt-2 1w-full" %>
  </div>
  <div class="my-5">
    <%= form.label :body %>
    <%= form.rich_text_area :body, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>
  <div>
    <%= form.label :pictures, style: "display: block" %>
    <%= form.file_field :pictures, multiple: true %>
  </div>
  <br />
  <div class="inline">
    <%= form.submit class: "rounded-lg py-2 px-3 bg-blue-600
    dark:text-slate-800 text-white inline-block font-medium cursor-pointer"
    %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Show this article", @article,
  class: "ml-2 rounded-lg py-2 px-3 bg-gray-100
  dark:text-slate-800 inline-block font-medium" %>
  <%= link_to "Back to articles", articles_path,
  class: "ml-2 rounded-lg py-2 px-3 bg-gray-100
  dark:text-slate-800 inline-block font-medium" %>
</div>

app/views/articles/i.html.erb
<% if @articles.first.title? %>
<% end %>
<div class="js-user-list-create-dialog-template"
data-label="Create list">
</div>

<div class="flex justify-between items-center">
  <%= link_to 'New article', new_article_path,
  class: "rounded-lg py-3 px-4 bg-blue-600
  text-white block font-medium" %>
</div>
<hr />
<div id="tag_cloud">
  <% tag_cloud Article.tag_counts, %w[s m l] do |tag, css_class| %>
    <%= link_to tag.name, tag_path(tag.id), #name),
    class: css_class %>
  <% end %>
</div>
Tag: <%= " Related count: (#{tag.articles.count}) " %>
tag.to_s +
<%= render @articles %>

app/views/articles/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>
  <br />
  <div class="flex justify-between tems-center">
    <h1 class="dark:text-slate-400 font-bold text-4xl">Novines</h1>
    <%= link_to 'New article', new_article_path,
    class: "rounded-lg py-3 px-4 bg-blue-600
    text-white block font-medium" %>
  </div>
  <h5>
    <a href="/articles/<%= @articles.first.id %>",
    class="nav-link"><%= @articles.first.title %></a>
  </h5>
  <% if @articles.first.image.attached? %>
    <%= link_to image_tag(@articles.first.image,
    style:"width:560px; heigh:auto; nav-link; nav-right;"),
    @articles.first.image %>
  <% end %>
  <hr />
  <%= form_with(url: articles_path, method: :get,
  data: {controller: "search-form",
  turbo_frame: "articles", turbo_action: "advance"}) do |form| %>
    <%= form.label :query, "Search by article title:",
    class: "block mb-2" %>
    <div class="flex space-x-3">
      <%= form.text_field :query, class: "py-2 px-4
      rounded border ring-0 focus:ring-4
      focus:ring-orange-100 focus:shadow-none
      dark:text-slate-800 focus:border-orange-500 focus:outline-none",
      data: {action: "input->search-form#search"} %>

      <%= form.submit 'Search', class: "px-4 py-2 font-medium
bg-orange-400 text-neutal-900 rounded flex items-center
cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0
focus:ring-orange-100" %>
    </div>
  <% end %>
  <hr />
  <% if @pagy.count > @pagy.items %>
  <div class="mt-10">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <hr />
  <% end %>
  <div id="articles" class="min-w-full">
    <% @articles.each do |article| %>
    <div class="row  mt-4 clearfix">
      <div class="col-8 col-sm-8 col-md-9 col-lg-9">
        <h5 class="mt-0 mb-1">
          <a href="/articles/<%= article.id %>",
          class="nav-link"><%= article.title %></a>
        </h5>
        <strong class="block font-medium mb-1">Tags:
        <% article.tags.each do |tag| %>
          <%= link_to tag, style:"text-decoretion:none" do %>
            <spat class="tag"><%= tag.name.capitalize %></spat>
          <% end %>
        <% end %>
        </strong>
        <time class="block dateline
        dark:text-slate-400 1text-muted" role="" itemprop="datePublished" datetime="28.03.2023 09:13" data-timestamp="1679987580">
          <small><%= article.publish %></small>
        </time>
        <%= truncate(strip_tags(article.body.to_s), length:180) %>
      </div>
      <div class="col-4 col-sm-4 col-md-3 col-lg-3 clearfix">
        <% if article.image.attached? %>
          <%= link_to image_tag(article.image,
          style:"width:200px; heigh:auto"), article.image %>
        <% end %>
      </div>
      <%= link_to "Edit this article", edit_article_path(article) %>
    </div>
    <% end %>
  </div>
  <% if @pagy.count > @pagy.items %>
  <hr />
  <div class="mt-1">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
  <hr />
  <% end %>
  <div class="flex justify-between items-center">
    <%= link_to 'New article', new_article_path,
    class: "rounded-lg py-3 px-4 bg-blue-600
    text-white block font-medium" %>
  </div>
  <br/>
</div>

app/views/articles/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New article</h1>

  <%= render "form", article: @article %>

  <%= link_to "Back to articles", articles_path,
  class: "ml-2 rounded-lg py-2 px-3 bg-gray-100
  dark:text-slate-800 inline-block font-medium" %>
</div>

app/views/articles/sh.html.erb
Art: <%= @article.tag.name %>
<div class="flex justify-between items-center">
<% if user_signed_in? %>
  <%= link_to 'Edit this article', edit_article_path(@article),
  class: "mt-2 rounded-lg py-2 px-4 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to 'Destroy this article', article_path(@article), method: :delete,
    class: "mt-2 rounded-lg py-2 px-4 bg-gray-100 font-medium" %>
  </div>
<% end %>
  <%= link_to 'Back to articles', articles_path,
  class: "ml-2 rounded-lg py-2 px-4 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= link_to "New article", new_article_path,
    class: "rounded-lg py-2 px-4 bg-blue-600 text-white block font-medium" %>
  </div>
</div>

<div class="flex justify-between items-center">
<% if user_signed_in? %>
  <%= link_to 'Edit this list', edit_list_path(@list), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= button_to 'Destroy this list', list_path(@list), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
  </div>
<% end %>
  <%= link_to 'Back to lists', lists_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <div class="inline-block ml-2">
    <%= link_to "New list", new_list_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
</div>
<% if user_signed_in? != admin_signed_in? %>
<% if admin_signed_in? %>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>
</div>
<% end %>
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @article %>

    <%= link_to "Edit this article", edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this article", article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to articles", articles_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/articles/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <br />
    <div class="1flex justify-between items-center">
      <% if user_signed_in? %>
        <%= link_to "Edit this article", edit_article_path(@article),
        class: "bg-green-700 mt-1 rounded-lg py-2 px-3
        text-white 1bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-1">
          <%= button_to "Destroy this article", article_path(@article), method: :delete,
          class: "bg-red-600 mt-1 rounded-lg py-2 px-3
          text-white 1bg-gray-100 font-medium" %>
        </div>
      <% end %>
      <%= link_to "Back to articles", articles_path,
      class: "bg-gray-500 ml-1 mt-1 rounded-lg py-2 px-3
      text-white 1bg-gray-100 1inline-block font-medium" %>
      <div class="inline-block ml-1">
        <%= link_to "New article", new_article_path,
        class: "bg-blue-700 mt-1 rounded-lg py-2 px-3
        1block inline-block font-medium text-white" %>
      </div>
    </div>
    <br />
    <h3 class="block 1font-medium mb-1 text-3xl">
      <%= @article.title %></h3>
    <h5 class="dark:text-slate-400 block font-medium mb-1 text-1xl">
      <%= @article.name %>
    </h5>
    <h6>
      <strong class="block font-medium mb-1">Tags:
      <% @article.tags.each do |tag| %>
        <%= link_to tag, style:"text-decoretion:none" do %>
          <spat class="tag"><%= tag.name.capitalize %></spat>
        <% end %>
      <% end %>
      </strong>
    </h6>
    <h6 class="block font-medium mb-1 text-1xl">
      <time class="block dateline
      dark:text-slate-400 1text-muted" role="" itemprop="datePublished" datetime="28.03.2023 09:13" data-timestamp="1679987580">
        <small><%= @article.publish %></small>
      </time>
    </h6>
    <br />
    <div id="navbar" class="1collapse">
      <ul class="nav navbar-nav">
        <li style="width:650px; heigh:auto" class="">
          <p style="width:650px; heigh:auto">
          <% if @article.image.attached? %>
            <%= link_to image_tag(@article.image,
            style:"width:640px; heigh:auto"), @article.image %>
          <% end %>
          </p>
        </li>
        <li class="">
          <p style="width:400px; heigh:200px">
            <%= @article.body %>
          </p>
          <br />
        </li>
        <li class="">
          <% if @article.pictures.attached? %>
            <% @article.pictures.each do |attachment| %>
              <% if attachment.image? %>
                <%= image_tag attachment, width: "200px" %>
              <% elsif attachment.audio? %>
                <audio controls>
                  <source src="<%= rails_blob_url(attachment) %>"
                    type="<%= attachment.content_type %>" />
                </audio>
              <% elsif attachment.video? %>
                <video controls width="720">
                  <source src="<%= rails_blob_url(attachment) %>"
                    type="<%= attachment.content_type %>" />
                </video>
              <% else %>
                <%= link_to attachment.filename,
                rails_blob_path(attachment, disposition: "attachment") %>
              <% end %>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
    <div class="1flex justify-between items-center">
      <% if user_signed_in? %>
        <%= link_to "Edit this article", edit_article_path(@article),
        class: "bg-green-700 mt-1 rounded-lg py-2 px-3
        text-white 1bg-gray-100 inline-block font-medium" %>
        <div class="inline-block ml-1">
          <%= button_to "Destroy this article", article_path(@article), method: :delete,
          class: "bg-red-600 mt-1 rounded-lg py-2 px-3
          text-white 1bg-gray-100 font-medium" %>
        </div>
      <% end %>
      <%= link_to "Back to articles", articles_path,
      class: "bg-gray-500 ml-1 mt-1 rounded-lg py-2 px-3
      text-white 1bg-gray-100 1inline-block font-medium" %>
      <div class="inline-block ml-1">
        <%= link_to "New article", new_article_path,
        class: "bg-blue-700 mt-1 rounded-lg py-2 px-3
        1block inline-block font-medium text-white" %>
      </div>
    </div>
    <br />
  </div>
</div>

app/views/articles/show1.html.erb
<br />
<% if user_signed_in? %>
<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>
</div>
<% end %>
<br />
<div class="flex justify-between items-center">
  <%= link_to 'New article', new_article_path,
  class: "rounded-lg py-3 px-5 bg-blue-600
  text-white block font-medium" %>
</div>
<hr />
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>
    <h3><%= @article.title %></h3>
    <h6><small><%= @article.name %></small></h6>
    <h5>
      <% if !@tags.nil? %>
        <% @tags.each  do |tags| %>
          <div style="margin-top:15px; margin-left:8px">
            <%= link_to tags.name, "/path1" %>
          </div>
        <% end%>
      <% end %>
      <strong class="block font-medium mb-1">Tags:</strong>
      <% @article.tags.each do |tag| %>
        <%= link_to tag, style:"text-decoretion:none" do %>
          <spat class="tag"><%= tag.name.capitalize %></spat>
        <% end %>
      <% end %>
    </h5>
    <time class="dateline text-muted" role="" itemprop="datePublished" datetime="28.03.2023 09:13" data-timestamp="1679987580">
      <small><%= @article.publish %></small>
    </time>
    <div id="navbar" class="1collapse">
      <ul class="nav navbar-nav">
        <li style="width:650px; heigh:auto" class="">
          <p style="width:650px; heigh:auto">
          <% if @article.image.attached? %>
            <%= link_to image_tag(@article.image,
            style:"width:640px; heigh:auto"), @article.image %>
          <% end %>
          </p>
        <li><hr /></li>
        <li class="">
          <p style="width:400px; heigh:200px">
            <%= @article.body %>
          </p>
        </li>
        <li class="">
          <% if @article.pictures.attached? %>
            <% @article.pictures.each do |attachment| %>
              <% if attachment.image? %>
                <%= image_tag attachment, width: "200px" %>
              <% elsif attachment.audio? %>
                <audio controls>
                  <source src="<%= rails_blob_url(attachment) %>"
                    type="<%= attachment.content_type %>" />
                </audio>
              <% elsif attachment.video? %>
                <video controls width="720">
                  <source src="<%= rails_blob_url(attachment) %>"
                    type="<%= attachment.content_type %>" />
                </video>
              <% else %>
                <%= link_to attachment.filename,
                rails_blob_path(attachment, disposition: "attachment") %>
              <% end %>
            <% end %>
          <% end %>
        </li>
      </ul>
    </div>
    <hr />
    <div class="flex justify-between items-center">
    <% if user_signed_in? %>
      <%= link_to 'Edit this article', edit_article_path(@article), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      <div class="inline-block ml-2">
        <%= button_to 'Destroy this article', article_path(@article), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
      </div>
    <% end %>
      <br />
      <%= link_to 'New article', new_article_path,
      class: "rounded-lg bg-blue-600
      text-white block font-medium" %> |
      <%= link_to 'Back to articles', articles_path %>
    </div>
    <br />
  </div>
</div>