config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  namespace :admin do
      resources :arts
      resources :articles
      resources :cats
      resources :lists
      resources :posts
      resources :tags
      resources :taggables
      resources :blogs
      resources :users

      root to: "arts#index"
    end
  resources :cats
  resources :posts
  resources :tags
  resources :articles
  get 'home/index'
  resources :arts
  devise_for :users
  resources :lists
  get "up" => "rails/health#show", as: :rails_health_check
  # root "posts#index"
  #root "lists#index"
  root "home#index"
  #root "arts#index"
  #root "cats#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/art.rb
class Art < ApplicationRecord
  async_pluck
  #async_count_by_sql
  validates :name, presence: true, uniqueness: true
  has_many :lists
end

app/models/article.rb
class Article < ApplicationRecord
  async_pluck
  belongs_to :user
  has_many :taggables, dependent: :destroy
  has_many :tags, through: :taggables
  has_one_attached :image
  has_many_attached :pictures
  has_rich_text :body
  accepts_nested_attributes_for :tags, allow_destroy: true,
   :reject_if => lambda { |a| a[:name].blank? }

  def image_as_thumbnail
    return unless image.content_type.in?(%w[image/jpeg image/png image/jpg])
    image.variant(resize_to_limit: [300, 300]).processed
  end
  def pictures_as_thumbnails
    pictures.map do |picture|
      picture.variant(resize_to_limit: [150, 150]).processed
    end
  end
  def pictures_as_thumbnails(article)
    article.variant(resize_to_limit: [200, 200]).processed
  end
end

app/models/blog.rb
class Blog < ApplicationRecord
  has_rich_text :body
end

app/models/cat.rb
class Cat < ApplicationRecord
  #attr_accessible :name, :parent
  has_ancestry
  validates :name, presence: true, uniqueness: true
  has_many :posts
  #accepts_nested_attributes_for :parents, reject_if: :all_blank, allow_destroy: true
  has_many :subcats, class_name: 'Cat',
   foreign_key: 'parent_id', :dependent => :destroy
  has_many :parents, inverse_of: :cat#:property
  belongs_to :parent, class_name: "Cat",
    foreign_key: :parent_id, optional: true
  has_many :children, class_name: "Cat",
    foreign_key: "parent_id"
  has_many :children, :class_name => 'Cat',
   :foreign_key => 'parent_id'
  #scope :top_level, where(:parent_id => nil)
  scope :roots, -> { where(parent_id: nil) }

   # Show subcategory
   def show
     @cat = Cat.find(params[:id])
       # Grab all sub-categories
     @cats = @cat.parent_cat
       # We want to reuse the index renderer:
     render :action => :index
   end

   def find_subcats
     @subcats = Cat.where(:parent_id =>
       params[:parent_id]).all
   end

   def descendents
     children.map do |child|
       [child] + child.descendents
     end.flatten
   end

   def self_and_descendents
     [self] + descendents
   end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :cat
  has_rich_text :body
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :taggables, dependent: :destroy
  has_many :articles, through: :taggables
  belongs_to :parent, class_name: "Tag", optional: true  #has_many :taggables, dependent: :destroy
  has_many :subordinates, class_name: "Tag",
    foreign_key: "parent_id", :dependent => :destroy

  def to_s
    name
  end
end

app/models/taggable.rb
class Taggable < ApplicationRecord
  belongs_to :article
  belongs_to :tag
  a = Taggable.where(tag_id: @tag_id)
  a.pluck(:article_id)
  #@post_ids = Taggable.where(tag_id: @tag_id).map(&:post_id)
  @article_ids = Taggable.where(tag_id: @tag_id).map(&:article_id)
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/arts_controller.rb
class ArtsController < ApplicationController
  before_action :set_art, only: %i[ show edit update destroy ]

  def index
    @arts = Art.all
    if params[:query].present?
      @arts = Art.where("name LIKE ?", "%#{params[:query]}%")
    end

    if turbo_frame_request?
      render partial: "arts",
      locals: { arts: @arts }
    else
      render :index
    end
  rescue Pagy::OverflowError
    #redirect_to root_path(page: 1)
    params[:page] = 1
    retry
  end

  # GET /arts/1 or /arts/1.json
  def show
  end

  # GET /arts/new
  def new
    @art = Art.new
  end

  # GET /arts/1/edit
  def edit
  end

  # POST /arts or /arts.json
  def create
    @art = Art.new(art_params)

    respond_to do |format|
      if @art.save
        format.html { redirect_to art_url(@art), notice: "Art was successfully created." }
        format.json { render :show, status: :created, location: @art }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /arts/1 or /arts/1.json
  def update
    respond_to do |format|
      if @art.update(art_params)
        format.html { redirect_to art_url(@art), notice: "Art was successfully updated." }
        format.json { render :show, status: :ok, location: @art }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @art.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /arts/1 or /arts/1.json
  def destroy
    @art.destroy!

    respond_to do |format|
      format.html { redirect_to arts_url, notice: "Art was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art
      @art = Art.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def art_params
      params.require(:art).permit(:name)
    end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :set_cat, only: %i[ show edit update destroy ]

  def index
    @cats = Cat.all
    @pagy, @cats = pagy(@cats)
    if params[:query].present?
      @cats = Cat.where("name LIKE ?", "%#{params[:query]}%")
    end

    if turbo_frame_request?
      render partial: "cats",
      locals: { cats: @cats }
    else
      render :index
    end

  rescue Pagy::OverflowError
    #redirect_to root_path(page: 1)
    params[:page] = 1
    retry
  end

  def show
  end

  def new
    @cat = Cat.new
  end

  def edit
  end

  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully created." }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_url(@cat), notice: "Cat was successfully updated." }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cat.destroy!

    respond_to do |format|
      format.html { redirect_to cats_url, notice: "Cat was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_cat
      @cat = Cat.find(params[:id])
    end

    def cat_params
      params.require(:cat).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend

  def subcat_prefix(depth)
    ("&nbsp;" * 4 * depth).html_safe
   end

   def tag_options_array(current_id = 0,tags=[], parent_id=0, depth=0)
    Tag.where('parent_id = ? AND id != ?', parent_id, current_id ).order(:id).each do |tag|
        tags << [subcat_prefix(depth) + tag.name, tag.id]
        tag_options_array(current_id,tags, tag.id, depth+1)
    end

    tags
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/arts_helper.rb
module ArtsHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/fields/trix_field/_form.html.erb
<div class="field-unit__label">
  <%= f.label field.attribute %>
</div>
<div class="field-unit__field">
  <%= f.trix_editor field.attribute %>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="<%=is_active('home')%> nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="<%=is_active('cats')%> nav-item">
          <a class="nav-link" aria-current="page" href="/cats/">Cat</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/6">Vijest</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/7">Sport</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/9">OKO</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/13">Politika</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/11">Muzika</a>
        </li>
        <li class="<%=is_active('arts')%> nav-item">
          <%= link_to 'Arts', arts_path,
          class: "nav-link" %>
        </li>
        <li class="<%=is_active('lists')%> nav-item">
          <%= link_to 'Lists', lists_path,
          class: "nav-link" %>
        </li>
        <% if user_signed_in? != admin_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Article', articles_path,
          class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="btn btn-primary nav-link dropdown-toggle" href="/cats"
          role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown button
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="/cats/1">Prodavnica</a></li>
            <li><a class="dropdown-item" href="/cats/2">Magazin</a></li>
            <li>
              <a class="dropdown-item" href="/cats/3">
                Program
              </a>
              <ul class="dropdown-menu dropdown-submenu">
                <li>
                  <a class="dropdown-item" href="/cats/23">C#</a>
                </li>
                <li>
                  <a class="dropdown-item" href="/cats/24">Ruby on Rails</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 3 &raquo; </a>
                  <ul class="dropdown-menu dropdown-submenu">
                    <li>
                      <a class="dropdown-item" href="#">Multi level 1</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Multi level 2</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 4</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 5</a>
                </li>
              </ul>
            </li>
            <li><a class="dropdown-item" href="/cats/19">Game</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Setting
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_user.email}",
               edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= link_to "Sign out", destroy_user_session_path,
              method: :delete, data: { turbo_method: :delete } %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_user_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_user_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <% if admin_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_admin.email}",
               edit_admin_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= link_to "Sign out", destroy_admin_session_path,
              method: :delete, data: { turbo_method: :delete } %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_admin_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_admin_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <%= form_with(url: articles_path, method: :get,
      data: {controller: "search-form",
      turbo_frame: "searchs", turbo_action: "advance"}) do |form| %>
        <div class="flex space-x-3">
          <%= form.text_field :query, class: "py-2 px-4
          rounded border ring-0 focus:ring-4
          focus:ring-orange-100 focus:shadow-none
          focus:border-orange-500 focus:outline-none",
          data: {action: "input->search-form#search"} %>

          <%= form.submit 'Search', class: "px-4 py-2 font-medium
      bg-orange-300 text-neutal-900 rounded flex items-center
      cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0
      focus:ring-orange-100" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_nav0.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="<%=is_active('home')%> nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="<%=is_active('cats')%> nav-item">
          <a class="nav-link" aria-current="page" href="/cats/">Cat</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/6">Vijest</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/7">Sport</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/9">OKO</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/13">Politika</a>
        </li>
        <li class="<%=is_active('tags')%> nav-item">
          <a class="nav-link" aria-current="page" href="/tags/11">Muzika</a>
        </li>
        <li class="<%=is_active('arts')%> nav-item">
          <%= link_to 'Arts', arts_path,
          class: "nav-link" %>
        </li>
        <li class="<%=is_active('lists')%> nav-item">
          <%= link_to 'Lists', lists_path,
          class: "nav-link" %>
        </li>
        <% if user_signed_in? != admin_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Article', articles_path,
          class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="btn btn-primary nav-link dropdown-toggle" href="/cats"
          role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown button
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <li><a class="dropdown-item" href="/cats/1">Prodavnica</a></li>
            <li><a class="dropdown-item" href="/cats/2">Magazin</a></li>
            <li>
              <a class="dropdown-item" href="/cats/3">
                Program
              </a>
              <ul class="dropdown-menu dropdown-submenu">
                <li>
                  <a class="dropdown-item" href="/cats/23">C#</a>
                </li>
                <li>
                  <a class="dropdown-item" href="/cats/24">Ruby on Rails</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 3 &raquo; </a>
                  <ul class="dropdown-menu dropdown-submenu">
                    <li>
                      <a class="dropdown-item" href="#">Multi level 1</a>
                    </li>
                    <li>
                      <a class="dropdown-item" href="#">Multi level 2</a>
                    </li>
                  </ul>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 4</a>
                </li>
                <li>
                  <a class="dropdown-item" href="#">Submenu item 5</a>
                </li>
              </ul>
            </li>
            <li><a class="dropdown-item" href="/cats/19">Game</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Setting
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_user.email}",
               edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= link_to "Sign out", destroy_user_session_path,
              method: :delete, data: { turbo_method: :delete } %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_user_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_user_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <% if admin_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_admin.email}",
               edit_admin_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= link_to "Sign out", destroy_admin_session_path,
              method: :delete, data: { turbo_method: :delete } %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_admin_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_admin_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <%= form_with(url: articles_path, method: :get,
      data: {controller: "search-form",
      turbo_frame: "searchs", turbo_action: "advance"}) do |form| %>
        <div class="flex space-x-3">
          <%= form.text_field :query, class: "py-2 px-4
          rounded border ring-0 focus:ring-4
          focus:ring-orange-100 focus:shadow-none
          focus:border-orange-500 focus:outline-none",
          data: {action: "input->search-form#search"} %>

          <%= form.submit 'Search', class: "px-4 py-2 font-medium
      bg-orange-300 text-neutal-900 rounded flex items-center
      cursor-pointer hover:bg-orange-400 focus:ring-4 ring-0
      focus:ring-orange-100" %>
        </div>
      <% end %>
    </div>
  </div>
</nav>

app/views/layouts/_navb.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Films</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Posts', posts_path,
          class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Setting
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_user.email}",
               edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= button_to(
                "Log Out",
                destroy_user_session_path,
                method: :delete
              ) %>            <% else %>
            <li>
              <%= link_to "Sign In",
               new_user_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_user_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/_navba.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Films</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/home/index">Home</a>
        </li>
        <li class="nav-item">
          <%= link_to 'Arts', arts_path,
          class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Lists', lists_path,
          class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Categories', cats_path,
          class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Tags', tags_path,
          class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Articles', articles_path,
          class: "nav-link" %>
        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Setting
          </a>
          <ul class="dropdown-menu">
            <% if user_signed_in? %>
            <li class="dropdown-item">
              <%= link_to "Hi, #{current_user.email}",
               edit_user_registration_path, class:'nav-link' %>
            </li>
            <li class="dropdown-item">
              <%= button_to(
                "Log Out",
                destroy_user_session_path,
                method: :delete
              ) %>
            <% else %>
            <li>
              <%= link_to "Sign In",
               new_user_session_path, class:'nav-link' %>
            </li>
            <li>
              <%= link_to "Sign Up",
               new_user_registration_path, class:'nav-link' %>
            </li>
            <% end %>
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/a.html.erb
dark:text-white
dark:text-slate-800
<%= image_tag("icons/_VS.svg",
class: 'w-72 h-80 hover:cursor-pointer',
data: { action: 'click->dark-mode#toggle'}) %>
<br />
<%= render 'layouts/color' %>
<div class="container mx-auto mt-1 px-2 flex">
  <%= render 'layouts/na' %>
</div>
<%= render 'layouts/navba' %>
<%= javascript_importmap_tags "application", "data-turbo-track": "reload", defer: true %>
<li class="nav-item">
  <%= link_to 'Cates', cates_path,
  class: "nav-link" %>
</li>
<li class="nav-item">
  <%= link_to 'Blogs', blogs_path,
  class: "nav-link" %>
</li>

<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="description" content="Cascading grid layout library">
<meta charset="utf-8">
<meta name="HandheldFriendly" content="true">
<meta name="referrer" content="no-referrer-when-downgrade">
<meta name="google-site-verification" content="BEqJtoPo_I4c_6vkFIVVSbpf9fVSUwI2wZwkVnTKd8k">
<meta name="alexaVerifyID" content="DaUAqrtPvA1Lu2A8fkUtlkjhrkY">
<meta name="msvalidate.01" content="EEA0E4EF924434B853F2B4249F0D045A">
<div class="container mx-auto mt-1 px-2 flex">
  <%= yield %>
</div>

<%= yield %>
<%= render 'layouts/navbar' %>

<%= button_to(
  "Log Out",
  destroy_user_session_path,
  method: :delete
) %>
<%= link_to "Sign out", destroy_user_session_path,
method: :delete, data: { turbo_method: :delete } %>